/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  admin: string;
  data?: Binary | null;
}
export type ExecuteMsg = {
  set_fee: {
    data: Binary;
    fee_name: string;
    fee_type: Fees;
    module_name: string;
  };
} | {
  remove_fee: {
    fee_name: string;
    fee_type: Fees;
    module_name: string;
  };
} | {
  distribute: {
    custom_payment_addresses?: CustomPaymentAddress[] | null;
    fee_type: Fees;
    module_name: string;
  };
} | {
  lock_execute: {};
} | {
  receive: Cw20ReceiveMsg;
};
export type Fees = "fixed" | "percentage";
export type Uint128 = string;
export interface CustomPaymentAddress {
  address: string;
  fee_name: string;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  config: {};
} | {
  percentage_fee: {
    fee_name: string;
    module_name: string;
  };
} | {
  fixed_fee: {
    fee_name: string;
    module_name: string;
  };
} | {
  percentage_fees: {
    limit?: number | null;
    module_name: string;
    start_after?: string | null;
  };
} | {
  fixed_fees: {
    limit?: number | null;
    module_name: string;
    start_after?: string | null;
  };
} | {
  total_percentage_fees: {
    limit?: number | null;
    module_name: string;
    start_after?: string | null;
  };
} | {
  total_fixed_fees: {
    limit?: number | null;
    module_name: string;
    start_after?: string | null;
  };
} | {
  keys: {
    fee_type: Fees;
    limit?: number | null;
    start_after?: string | null;
  };
};
export type Addr = string;
export interface ResponseWrapperForConfig {
  data: Config;
  query: string;
}
export interface Config {
  admin: Addr;
}
export interface ResponseWrapperForFixedFeeResponse {
  data: FixedFeeResponse;
  query: string;
}
export interface FixedFeeResponse {
  address?: string | null;
  fee_name: string;
  module_name: string;
  value: Uint128;
}
export interface ResponseWrapperForArrayOfFixedFeeResponse {
  data: FixedFeeResponse[];
  query: string;
}
export interface ResponseWrapperForArrayOfString {
  data: string[];
  query: string;
}
export type Decimal = string;
export interface ResponseWrapperForPercentageFeeResponse {
  data: PercentageFeeResponse;
  query: string;
}
export interface PercentageFeeResponse {
  address?: string | null;
  fee_name: string;
  module_name: string;
  value: Decimal;
}
export interface ResponseWrapperForArrayOfPercentageFeeResponse {
  data: PercentageFeeResponse[];
  query: string;
}
export interface ResponseWrapperForUint128 {
  data: Uint128;
  query: string;
}
export interface ResponseWrapperForDecimal {
  data: Decimal;
  query: string;
}