/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  admin: string;
  data?: Binary | null;
}
export type ExecuteMsg = {
  register_module: {
    code_id: number;
    module: string;
    msg?: Binary | null;
  };
} | {
  update_hub_info: {
    description: string;
    external_link?: string | null;
    image: string;
    name: string;
  };
} | {
  deregister_module: {
    module: string;
  };
} | {
  update_operators: {
    addrs: string[];
  };
} | {
  migrate_contracts: {
    code_id: number;
    contract_address: string;
    msg: Binary;
  };
};
export type QueryMsg = {
  config: {};
} | {
  module_address: {
    module: string;
  };
} | {
  operators: {};
};
export interface MigrateMsg {}
export interface ResponseWrapperForConfigResponse {
  data: ConfigResponse;
  query: string;
}
export interface ConfigResponse {
  admin: string;
  hub_info: HubInfo;
}
export interface HubInfo {
  description: string;
  external_link?: string | null;
  image: string;
  name: string;
}
export interface ResponseWrapperForString {
  data: string;
  query: string;
}
export interface ResponseWrapperForArrayOfString {
  data: string[];
  query: string;
}