/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Timestamp = Uint64;
export type Uint64 = string;
export interface InstantiateMsg {
  config: WhitelistConfig;
  members: string[];
}
export interface WhitelistConfig {
  end_time: Timestamp;
  member_limit: number;
  per_address_limit: number;
  start_time: Timestamp;
}
export type ExecuteMsg = {
  update_whitelist_config: {
    whitelist_config: WhitelistConfig;
  };
} | {
  add_members: {
    members: string[];
  };
} | {
  remove_members: {
    members: string[];
  };
};
export type QueryMsg = {
  config: {};
} | {
  members: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  is_active: {};
} | {
  is_member: {
    member: string;
  };
};
export interface MigrateMsg {}
export interface ResponseWrapperForConfigResponse {
  data: ConfigResponse;
  query: string;
}
export interface ConfigResponse {
  admin: string;
  end_time: Timestamp;
  is_active: boolean;
  member_limit: number;
  member_num: number;
  per_address_limit: number;
  start_time: Timestamp;
}
export interface ResponseWrapperForBoolean {
  data: boolean;
  query: string;
}
export interface ResponseWrapperForArrayOfString {
  data: string[];
  query: string;
}