/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin: string;
}
export type ExecuteMsg = {
  register_permission: {
    code_id: number;
    msg: Binary;
    permission: string;
  };
} | {
  update_module_permissions: {
    module: string;
    permissions: string[];
  };
} | {
  update_operators: {
    addrs: string[];
  };
} | {
  check: {
    module: string;
    msg: Binary;
  };
};
export type Binary = string;
export type QueryMsg = {
  permission_address: {
    permission: string;
  };
} | {
  module_permissions: Modules;
} | {
  operators: {};
};
export type Modules = "hub" | "mint" | "permission" | "swap" | "merge" | "marketplace" | "fee";
export interface MigrateMsg {}
export interface ResponseWrapperForArrayOfString {
  data: string[];
  query: string;
}
export interface ResponseWrapperForString {
  data: string;
  query: string;
}