/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./FeeModule.types";
import * as _1 from "./FeeModule.client";
import * as _2 from "./HubModule.types";
import * as _3 from "./HubModule.client";
import * as _4 from "./MarketplaceModule.types";
import * as _5 from "./MarketplaceModule.client";
import * as _6 from "./MergeModule.types";
import * as _7 from "./MergeModule.client";
import * as _8 from "./MetadataModule.types";
import * as _9 from "./MetadataModule.client";
import * as _10 from "./MintModule.types";
import * as _11 from "./MintModule.client";
import * as _12 from "./PermissionModule.types";
import * as _13 from "./PermissionModule.client";
import * as _14 from "./TokenModule.types";
import * as _15 from "./TokenModule.client";
import * as _16 from "./WhitelistModule.types";
import * as _17 from "./WhitelistModule.client";
import * as _18 from "./AttributePermission.types";
import * as _19 from "./AttributePermission.client";
import * as _20 from "./LinkPermission.types";
import * as _21 from "./LinkPermission.client";
import * as _22 from "./OwnershipPermission.types";
import * as _23 from "./OwnershipPermission.client";
export namespace contracts {
  export const FeeModule = { ..._0,
    ..._1
  };
  export const HubModule = { ..._2,
    ..._3
  };
  export const MarketplaceModule = { ..._4,
    ..._5
  };
  export const MergeModule = { ..._6,
    ..._7
  };
  export const MetadataModule = { ..._8,
    ..._9
  };
  export const MintModule = { ..._10,
    ..._11
  };
  export const PermissionModule = { ..._12,
    ..._13
  };
  export const TokenModule = { ..._14,
    ..._15
  };
  export const WhitelistModule = { ..._16,
    ..._17
  };
  export const AttributePermission = { ..._18,
    ..._19
  };
  export const LinkPermission = { ..._20,
    ..._21
  };
  export const OwnershipPermission = { ..._22,
    ..._23
  };
}