/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin?: string | null;
  hub_info: HubInfo;
  marbu_fee_module?: string | null;
}
export interface HubInfo {
  description: string;
  external_link?: string | null;
  image: string;
  name: string;
}
export type ExecuteMsg = {
  register_module: {
    code_id: number;
    module: string;
    msg: Binary;
  };
} | {
  update_hub_info: {
    description: string;
    external_link?: string | null;
    image: string;
    name: string;
  };
} | {
  update_website_config: {
    background_color?: string | null;
    background_image?: string | null;
    banner_image?: string | null;
  };
} | {
  deregister_module: {
    module: string;
  };
} | {
  update_operators: {
    addrs: string[];
  };
};
export type Binary = string;
export type QueryMsg = {
  config: {};
} | {
  module_address: {
    module: string;
  };
} | {
  operators: {};
};
export interface MigrateMsg {}
export interface ResponseWrapperForConfigResponse {
  data: ConfigResponse;
  query: string;
}
export interface ConfigResponse {
  admin: string;
  hub_info: HubInfo;
  website_config?: WebsiteConfig | null;
}
export interface WebsiteConfig {
  background_color?: string | null;
  background_image?: string | null;
  banner_image?: string | null;
}
export interface ResponseWrapperForString {
  data: string;
  query: string;
}
export interface ResponseWrapperForArrayOfString {
  data: string[];
  query: string;
}