/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  admin: string;
  data?: Binary | null;
}
export type ExecuteMsg = {
  update_buy_lock: {
    lock: boolean;
  };
} | {
  list_fixed_token: {
    collection_id: number;
    price: Uint128;
    token_id: number;
  };
} | {
  delist_fixed_token: {
    collection_id: number;
    token_id: number;
  };
} | {
  update_price: {
    collection_id: number;
    listing_type: Listing;
    price: Uint128;
    token_id: number;
  };
} | {
  buy: {
    collection_id: number;
    listing_type: Listing;
    token_id: number;
  };
} | {
  permission_buy: {
    buyer: string;
    collection_id: number;
    listing_type: Listing;
    token_id: number;
  };
} | {
  update_operators: {
    addrs: string[];
  };
} | {
  lock_execute: {};
} | {
  receive: Cw20ReceiveMsg;
};
export type Uint128 = string;
export type Listing = "fixed" | "auction";
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  config: {};
} | {
  fixed_listing: {
    collection_id: number;
    token_id: number;
  };
} | {
  fixed_listings: {
    collection_id: number;
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  operators: {};
};
export interface MigrateMsg {}
export type Addr = string;
export interface ResponseWrapperForConfig {
  data: Config;
  query: string;
}
export interface Config {
  admin: Addr;
  buy_lock: boolean;
}
export interface ResponseWrapperForFixedListing {
  data: FixedListing;
  query: string;
}
export interface FixedListing {
  collection_id: number;
  owner: Addr;
  price: Uint128;
  token_id: number;
}
export interface ResponseWrapperForArrayOfFixedListing {
  data: FixedListing[];
  query: string;
}
export interface ResponseWrapperForArrayOfString {
  data: string[];
  query: string;
}